name: sixcomputer
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  bot_toast: ^4.1.3
  cloud_firestore: ^4.17.0
  dio: ^5.4.3+1
  firebase_core: ^2.30.0
  firebase_database: ^10.5.4
  firebase_storage: ^11.7.3
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  fluttertoast: ^8.2.5
  image_picker: ^1.1.0
  intl: ^0.18.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
