// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKmxddiyyDLJCwXmNGwoceE8HXtucKg4w',
    appId: '1:108250033649:web:934f8e5c8bf178807f2850',
    messagingSenderId: '108250033649',
    projectId: 'sunny-idiom-396503',
    authDomain: 'sunny-idiom-396503.firebaseapp.com',
    databaseURL: 'https://sunny-idiom-396503-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sunny-idiom-396503.appspot.com',
    measurementId: 'G-0NWJNXRH8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByPfZK-9JyBxPqeKf9z5NHOosMV17WFN8',
    appId: '1:108250033649:android:72b25a6b3775c9d17f2850',
    messagingSenderId: '108250033649',
    projectId: 'sunny-idiom-396503',
    databaseURL: 'https://sunny-idiom-396503-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sunny-idiom-396503.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx_Ww9um6dvdTHeRxPT18ZHenjbaHllxM',
    appId: '1:108250033649:ios:d7f4a39d812e535a7f2850',
    messagingSenderId: '108250033649',
    projectId: 'sunny-idiom-396503',
    databaseURL: 'https://sunny-idiom-396503-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sunny-idiom-396503.appspot.com',
    iosBundleId: 'com.example.sixcomputer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx_Ww9um6dvdTHeRxPT18ZHenjbaHllxM',
    appId: '1:108250033649:ios:d7f4a39d812e535a7f2850',
    messagingSenderId: '108250033649',
    projectId: 'sunny-idiom-396503',
    databaseURL: 'https://sunny-idiom-396503-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sunny-idiom-396503.appspot.com',
    iosBundleId: 'com.example.sixcomputer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKmxddiyyDLJCwXmNGwoceE8HXtucKg4w',
    appId: '1:108250033649:web:fd863fa3f323d74b7f2850',
    messagingSenderId: '108250033649',
    projectId: 'sunny-idiom-396503',
    authDomain: 'sunny-idiom-396503.firebaseapp.com',
    databaseURL: 'https://sunny-idiom-396503-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sunny-idiom-396503.appspot.com',
    measurementId: 'G-XFNDRJX791',
  );

}